"""Generate Docker deployment kit for Sarva cloud projects."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _detect_stack(root: Path) -> dict[str, Any]:
    has_python = (root / "requirements.txt").exists() or (root / "pyproject.toml").exists()
    has_node = (root / "package.json").exists()
    has_docker = (root / "Dockerfile").exists()
    return {
        "python": has_python,
        "node": has_node,
        "has_dockerfile": has_docker,
    }


def generate_deploy_kit(root: Path, *, project_name: str = "app") -> dict[str, Any]:
    """Write deployment files into project root. Returns summary."""
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    stack = _detect_stack(root)
    written: list[str] = []

    if stack["python"] and not stack["has_dockerfile"]:
        dockerfile = f"""# Generated by Sarva — {project_name}
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PORT=8000
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
        (root / "Dockerfile").write_text(dockerfile, encoding="utf-8")
        written.append("Dockerfile")

    if not (root / "docker-compose.yml").exists():
        compose = f"""# Generated by Sarva — {project_name}
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
"""
        (root / "docker-compose.yml").write_text(compose, encoding="utf-8")
        written.append("docker-compose.yml")

    if not (root / ".env.example").exists():
        env_example = """# Copy to .env — never commit real secrets
PORT=8000
DATABASE_URL=
JWT_SECRET=change-me
"""
        (root / ".env.example").write_text(env_example, encoding="utf-8")
        written.append(".env.example")

    deploy_md = f"""# Deploy {project_name}

Generated by **Sarva** (Aitotech). Target: Docker on E2E Networks or any Linux VM.

## Prerequisites
- Docker and Docker Compose installed on the server
- Domain DNS pointed to your server (optional)

## Steps

1. Copy project files to the server (git clone or zip upload).
2. Create `.env` from `.env.example` and fill secrets.
3. Build and run:

```bash
docker compose up -d --build
```

4. Open `http://YOUR_SERVER_IP:8000` (or configure nginx + TLS).

## E2E Networks (India)
- API VM: Delhi region
- GPU inference (Sarva): separate service — see Sarva docs/E2E_DEPLOY.md

## Health check
```bash
curl -f http://127.0.0.1:8000/health || curl -f http://127.0.0.1:8000/
```
"""
    (root / "DEPLOY.md").write_text(deploy_md, encoding="utf-8")
    written.append("DEPLOY.md")

    k8s_dir = root / "deploy" / "k8s"
    k8s_dir.mkdir(parents=True, exist_ok=True)
    if not (k8s_dir / "deployment.yaml").exists():
        k8s = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {project_name.replace("_", "-")[:32]}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {project_name.replace("_", "-")[:32]}
  template:
    metadata:
      labels:
        app: {project_name.replace("_", "-")[:32]}
    spec:
      containers:
        - name: app
          image: YOUR_REGISTRY/{project_name}:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {project_name.replace("_", "-")[:32]}-env
---
apiVersion: v1
kind: Service
metadata:
  name: {project_name.replace("_", "-")[:32]}
spec:
  selector:
    app: {project_name.replace("_", "-")[:32]}
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
"""
        (k8s_dir / "deployment.yaml").write_text(k8s, encoding="utf-8")
        written.append("deploy/k8s/deployment.yaml")

    return {
        "ok": True,
        "stack": stack,
        "files_written": written,
        "message": f"Deploy kit ready: {', '.join(written)}",
    }
